"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArrowDownRight, ArrowRight, Bell, Check, CheckCheck, ChevronRight, CircleCheck, Clock3, Expand, FlaskConical, Footprints, LoaderCircle, MapPin, RotateCcw, ScanLine, Send, ShieldCheck, Siren, Sparkles, TriangleAlert, Video, X, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { hourlyData, initialStats, safetyAnalysis, type Incident, type Zone } from "@/lib/call-help/mock-data";
import { generateAIAnalysis } from "@/lib/call-help/demo-api";
import WarehouseScene from "./WarehouseScene";

export const formatTime = (timestamp: string, seconds = false) => new Date(timestamp).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", ...(seconds ? { second: "2-digit" } : {}) });
export function StatusBadge({ status, children }: { status: string; children?: React.ReactNode }) { return <span className={`status-badge ${status}`}><i/>{children || status}</span>; }
export function TopNav({ active, onNotifications }: { active: boolean; onNotifications: () => void }) {
  const [now, setNow] = useState<Date | null>(null);
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer); }, []);
  return <header className="top-nav"><div className="brand"><div className="brand-icon"><Activity size={24}/></div><div><div className="brand-name">CALL<span>-</span>HELP</div><div className="brand-tagline">AI Industrial Transit Safety</div></div></div><div className="online-indicator"><i/> SYSTEM ONLINE</div><div className="nav-right"><div className="nav-clock"><Clock3 size={14}/><span>{now ? now.toLocaleTimeString("en-US", { hour12: false }) : "--:--:--"}</span><small>LOCAL</small></div><span className="nav-divider"/><button className="icon-button notification-button" aria-label="View notifications" onClick={onNotifications}><Bell size={19}/>{active && <i/>}</button><span className="demo-badge"><FlaskConical size={13}/> Demo Mode</span></div></header>;
}
export function LiveCameraPanel({ zone, incidentActive, simulationDisabled, time, onSimulate, onReset }: { zone: Zone; incidentActive: boolean; simulationDisabled: boolean; time: string; onSimulate: () => void; onReset: () => void }) {
  const [expanded, setExpanded] = useState(false);
  useEffect(() => { if (!expanded) return; const key = (e: KeyboardEvent) => { if (e.key === "Escape") setExpanded(false); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [expanded]);
  return <section className={`panel camera-panel ${incidentActive ? "camera-alert" : ""} ${expanded ? "camera-expanded" : ""}`} id="live-camera"><div className="panel-heading"><div><h2><Video size={15}/> LIVE MONITORING</h2><p><MapPin size={12}/>{zone.name}<span className="muted-dot">·</span> North facility</p></div><div className="camera-heading-right"><span className="camera-count">01 / 04</span><button className="icon-button" aria-label={expanded ? "Exit expanded camera" : "Expand camera"} onClick={() => setExpanded(!expanded)}>{expanded ? <X size={17}/> : <Expand size={16}/>}</button></div></div><div className={`camera-view ${incidentActive ? "critical" : ""}`}><WarehouseScene fallen={incidentActive}/><div className="camera-vignette"/><div className="camera-overlay-top"><span className="camera-id"><Video size={13}/> CAM {zone.id === "02" ? "01" : zone.id === "01" ? "02" : zone.id}</span><span className="live-label"><i/> LIVE</span></div><div className={`detection-box ${incidentActive ? "fallen" : ""}`}><span className="detection-label">{incidentActive ? "FALL DETECTED" : "PERSON"}<b>{incidentActive ? "94%" : "98%"}</b></span><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/></div>{incidentActive && <div className="camera-warning"><TriangleAlert size={16}/> HUMAN DOWN DETECTED</div>}<div className="camera-bottom"><span>{time || "2026-10-03 14:32:08"}</span><span>1920 × 1080 <i/> 30 FPS</span></div><span className="scene-label">SIMULATED CAMERA FEED</span></div><div className="camera-controls"><div className="vision-status"><ScanLine size={15}/><span>Vision model active</span><i/><span className="vision-latency">32 ms latency</span></div><div className="demo-controls"><button className="button simulate-button" disabled={simulationDisabled} onClick={onSimulate}><Zap size={14}/>{simulationDisabled ? "Incident active" : "Simulate Fall"}</button><button className="reset-button" onClick={onReset}><RotateCcw size={13}/> Reset Demo</button></div></div></section>;
}
export function ActiveIncidentCard({ incident, onAcknowledge, onDispatch, onCamera }: { incident?: Incident; onAcknowledge: () => void; onDispatch: () => void; onCamera: () => void }) {
  return <section className={`panel active-panel ${incident ? "active-critical" : ""}`}><div className="panel-heading"><h2><Siren size={15}/> INCIDENT RESPONSE</h2><span className={`tiny-indicator ${incident ? "red" : ""}`}/></div>{!incident ? <div className="all-clear"><div className="safe-orbit"><div><ShieldCheck size={39} strokeWidth={1.4}/></div><i/></div><StatusBadge status="normal">ALL CLEAR</StatusBadge><h3>No active incident</h3><p>All monitored transit zones<br/>operating normally.</p><div className="all-clear-footer"><CheckCheck size={14}/><span>Automatic detection is standing by</span></div></div> : <div className="incident-content"><div className="incident-title"><div><StatusBadge status="critical">ACTIVE INCIDENT</StatusBadge><h3>Worker Down</h3></div><TriangleAlert size={30}/></div><div className="incident-meta"><div><span>Location</span><b>{incident.zone}</b></div><div><span>Detected</span><b>{formatTime(incident.timestamp, true)}</b></div><div><span>AI confidence</span><b>94% <span className="confidence-bar"/></b></div><div><span>Risk level</span><b className="red-text">CRITICAL</b></div></div><div className={`response-state ${incident.status}`}><span><i/>{incident.status === "dispatched" ? "RESPONSE DISPATCHED" : incident.status.toUpperCase()}</span>{(incident.dispatchedAt || incident.acknowledgedAt) && <small>{formatTime((incident.dispatchedAt || incident.acknowledgedAt)!, true)}</small>}</div><div className="incident-actions"><button className="button secondary" onClick={onAcknowledge} disabled={incident.status !== "unacknowledged"}><Check size={14}/> Acknowledge</button><button className="button dispatch" onClick={onDispatch} disabled={incident.status === "dispatched"}><Send size={14}/>{incident.status === "dispatched" ? "Dispatched" : "Dispatch Response"}</button></div><button className="view-camera" onClick={onCamera}><Video size={14}/> View Camera <ArrowRight size={13}/></button></div>}</section>;
}
export function ZoneStatusPanel({ zones, selected, onSelect }: { zones: Zone[]; selected: string; onSelect: (zone: Zone) => void }) {
  return <section className="panel zones-panel"><div className="panel-heading"><h2><MapPin size={15}/> TRANSIT ZONES</h2><span className="small-label">{zones.length} MONITORED</span></div><div className="zone-list">{zones.map(zone => <button className={`zone-row ${selected === zone.id ? "selected" : ""} ${zone.status}`} key={zone.id} onClick={() => onSelect(zone)}><span className="zone-icon">{zone.status === "critical" ? <TriangleAlert size={17}/> : <ScanLine size={17}/>}</span><span className="zone-info"><b>{zone.name}</b><span><i/>{zone.status === "critical" ? "CRITICAL" : "Normal"}<em>·</em>{zone.incidentsToday} {zone.incidentsToday === 1 ? "incident" : "incidents"} today</span></span><ChevronRight size={15}/></button>)}</div><div className="panel-footnote"><i/> All cameras connected <span>4 / 4</span></div></section>;
}
export function SafetyStats({ addedFalls }: { addedFalls: number }) {
  const data = hourlyData.map(item => ({ ...item, incidents: item.incidents + (item.hour === "4 PM" ? addedFalls : 0) }));
  return <section className="panel stats-panel"><div className="panel-heading"><h2><Activity size={15}/> TODAY’S SAFETY STATISTICS</h2><span className="small-label">TODAY</span></div><div className="stats-grid">{[{ label: "Incidents Today", value: initialStats.incidents + addedFalls, icon: Siren, color: "blue" }, { label: "Falls", value: initialStats.falls + addedFalls, icon: Footprints, color: "amber" }, { label: "Near-Falls", value: initialStats.nearFalls, icon: Activity, color: "amber" }, { label: "Avg Response", value: initialStats.response, icon: Clock3, color: "green", unit: "sec" }].map(stat => <div className="stat" key={stat.label}><span className={`stat-icon ${stat.color}`}><stat.icon size={15}/></span><span className="stat-value">{stat.value}<small>{stat.unit}</small></span><span className="stat-label">{stat.label}</span></div>)}</div><div className="chart-title"><span>Incidents by hour</span><span><i/> Incidents</span></div><div className="hour-chart"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{ top: 8, right: 10, left: -25, bottom: 0 }}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#83ada3" stopOpacity={.18}/><stop offset="100%" stopColor="#83ada3" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#263032" strokeDasharray="3 5"/><XAxis dataKey="hour" axisLine={false} tickLine={false} tick={{ fill: "#727f83", fontSize: 10 }} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#727f83", fontSize: 10 }} allowDecimals={false}/><Tooltip contentStyle={{ background: "#192225", border: "1px solid #39464a", borderRadius: 8, color: "#e4eded", fontSize: 12 }} cursor={{ stroke: "#5f7774" }}/><Area type="monotone" dataKey="incidents" name="Incidents" stroke="#9bbeb2" strokeWidth={2} fill="url(#chart-fill)" dot={{ r: 3, fill: "#b7d0c6", strokeWidth: 2, stroke: "#1a2526" }} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section>;
}
export function IncidentTimeline({ incidents, onSelect }: { incidents: Incident[]; onSelect: (incident: Incident) => void }) {
  return <section className="panel timeline-panel"><div className="panel-heading"><h2><Clock3 size={15}/> RECENT INCIDENTS</h2><span className="small-label">{incidents.length} EVENTS</span></div><div className="timeline-list">{incidents.map(incident => <button key={incident.id} className="timeline-row" onClick={() => onSelect(incident)}><span className={`timeline-node ${incident.severity}`}><i/></span><span className="timeline-body"><span className="timeline-top"><b>{incident.eventType}</b><time>{formatTime(incident.timestamp)}</time></span><span className="timeline-location">{incident.zone}</span><span className={`timeline-status ${incident.status === "resolved" ? "resolved" : incident.severity}`}>{incident.status === "resolved" ? "Resolved" : incident.status === "dispatched" ? "Response dispatched" : incident.severity === "critical" ? "Critical" : "Warning"}</span></span><ChevronRight size={13}/></button>)}</div></section>;
}
export function AISafetyInsights() {
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<typeof safetyAnalysis | null>(null);
  const generation = useRef(0);
  useEffect(() => () => { generation.current++; }, []);
  async function analyze() { setLoading(true); const request = ++generation.current; const result = await generateAIAnalysis(); if (request === generation.current) { setAnalysis(result); setLoading(false); } }
  return <section className="panel ai-panel"><div className="ai-header"><div className="ai-heading"><span className="ai-icon"><Sparkles size={21}/></span><div><h2>AI SAFETY ANALYSIS <span className="ai-tag">PATTERN INTELLIGENCE</span></h2><p>Turn incident history into a safer workplace.</p></div></div><button className="button analyze-button" disabled={loading} onClick={analyze}>{loading ? <LoaderCircle size={15} className="spin"/> : <Sparkles size={15}/>} {loading ? "Analyzing incident history..." : "Analyze Safety Pattern"}{!loading && <ArrowRight size={14}/>}</button></div><div aria-live="polite">{analysis ? <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="analysis-result"><div><span className="analysis-eyebrow">PATTERN IDENTIFIED</span><h3>Afternoon transit activity warrants review</h3><p>{analysis.summary}</p><p>{analysis.detail}</p><span className="mock-analysis-label">Demo analysis · illustrative recorded patterns</span></div><div><span className="analysis-eyebrow">RECOMMENDED INVESTIGATION</span><ul>{analysis.recommendations.map(item => <li key={item}><ArrowDownRight size={13}/>{item}</li>)}</ul></div></motion.div> : <div className="ai-empty"><span><span className="mini-sparkle">✧</span> A clearer picture, beyond the live feed.</span><p>Analyze recorded incidents to identify recurring zones, activity windows, and opportunities for safety review.</p><div className="ai-capabilities"><span><MapPin size={12}/> Zone patterns</span><span><Clock3 size={12}/> Activity windows</span><span><ShieldCheck size={12}/> Safety recommendations</span></div></div>}</div><div className="ai-disclaimer"><ShieldCheck size={12}/> AI insights are based on recorded incident patterns and should support, not replace, professional safety review.</div></section>;
}
export function IncidentDrawer({ incident, onDismiss, onResolve }: { incident: Incident | null; onDismiss: () => void; onResolve: (id: string) => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!incident) return; const previous = document.activeElement as HTMLElement; closeRef.current?.focus(); const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => { if (e.key === "Escape") onDismiss(); if (e.key === "Tab") { const items = document.querySelectorAll<HTMLButtonElement>(".incident-drawer button"); const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = old; document.removeEventListener("keydown", key); previous?.focus(); }; }, [incident, onDismiss]);
  return <AnimatePresence>{incident && <div className="drawer-layer"><motion.button aria-label="Dismiss incident details" className="drawer-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onDismiss}/><motion.aside className="incident-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: .22 }}><div className="drawer-header"><h2 id="drawer-title">Incident details</h2><button ref={closeRef} className="icon-button" aria-label="Close drawer" onClick={onDismiss}><X size={20}/></button></div><StatusBadge status={incident.status === "resolved" ? "normal" : incident.severity}>{incident.status === "resolved" ? "RESOLVED" : incident.severity.toUpperCase()}</StatusBadge><h3>{incident.eventType}</h3><div className="drawer-details">{[["Incident ID", incident.id], ["Event Type", incident.eventType], ["Zone", incident.zone], ["Time", formatTime(incident.timestamp, true)], ["Confidence", `${incident.confidence}%`], ["Response Status", incident.status === "dispatched" ? "Dispatched" : incident.status]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><h4>Detection Signals</h4><ul className="signals">{(incident.eventType === "Worker Down" ? ["Rapid vertical body movement", "Horizontal body orientation", "Low body position sustained for 1.8 seconds"] : incident.eventType === "Near Fall" ? ["Abrupt body orientation change", "Temporary loss of stable posture", "Standing posture recovered"] : ["Object within marked transit corridor", "Obstruction persisted across frames", "Active transit path partially blocked"]).map(signal => <li key={signal}><ScanLine size={14}/>{signal}</li>)}</ul><div className="drawer-summary"><h4><Sparkles size={16}/> AI Summary</h4><p>{incident.eventType === "Worker Down" ? "Computer vision detected a rapid body drop followed by sustained low horizontal posture within the monitored transit corridor." : incident.eventType === "Near Fall" ? "Computer vision recorded a brief change in body stability followed by recovery to standing posture in the monitored zone." : "Computer vision recorded a persistent obstruction within the marked transit path."}</p></div><button className="button resolve-button" disabled={incident.status === "resolved"} onClick={() => onResolve(incident.id)}><CircleCheck size={16}/>{incident.status === "resolved" ? "Incident Closed" : "Close Incident"}</button><p className="drawer-note">Demo record · Review conditions before resolving.</p></motion.aside></div>}</AnimatePresence>;
}
export function AlertToast({ toast, onDismiss }: { toast: { title: string; message: string; critical?: boolean } | null; onDismiss: () => void }) {
  return <AnimatePresence>{toast && <motion.div role="alert" className={`alert-toast ${toast.critical ? "critical" : ""}`} initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}><span className="toast-icon">{toast.critical ? <TriangleAlert size={21}/> : <CircleCheck size={21}/>}</span><div><b>{toast.title}</b><p>{toast.message}</p></div><button className="icon-button" aria-label="Dismiss notification" onClick={onDismiss}><X size={16}/></button></motion.div>}</AnimatePresence>;
}
