"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArrowDownRight, ArrowRight, Bell, Check, CheckCheck, ChevronRight, CircleCheck, Clock3, Expand, FlaskConical, Footprints, LoaderCircle, MapPin, RotateCcw, ScanLine, Send, ShieldCheck, Siren, Sparkles, TriangleAlert, Video, X, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { Incident, Zone } from "@/lib/call-help/types";
import { askSafetyCoach } from "@/lib/call-help/api";
import WarehouseScene from "./WarehouseScene";

export const formatTime = (timestamp: string, seconds = false) => new Date(timestamp).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", ...(seconds ? { second: "2-digit" } : {}) });
export function StatusBadge({ status, children }: { status: string; children?: React.ReactNode }) { return <span className={`status-badge ${status}`}><i/>{children || status}</span>; }
export function TopNav({ active, backendOnline, realtimeOnline, onNotifications }: { active: boolean; backendOnline: boolean; realtimeOnline: boolean; onNotifications: () => void }) {
  const [now, setNow] = useState<Date | null>(null);
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer); }, []);
  return <header className="top-nav"><div className="brand"><div className="brand-icon"><Activity size={24}/></div><div><div className="brand-name">CALL<span>-</span>HELP</div><div className="brand-tagline">AI Industrial Transit Safety</div></div></div><div className={`online-indicator ${backendOnline ? "" : "offline"}`}><i/> {backendOnline ? (realtimeOnline ? "SYSTEM ONLINE" : "API ONLINE") : "BACKEND OFFLINE"}</div><div className="nav-right"><div className="nav-clock"><Clock3 size={14}/><span>{now ? now.toLocaleTimeString("en-US", { hour12: false }) : "--:--:--"}</span><small>LOCAL</small></div><span className="nav-divider"/><button className="icon-button notification-button" aria-label="View notifications" onClick={onNotifications}><Bell size={19}/>{active && <i/>}</button><span className="demo-badge"><FlaskConical size={13}/> Demo Mode</span></div></header>;
}
export function LiveCameraPanel({ zone, incidentActive, simulationDisabled, time, onSimulate, backendOnline, realtimeOnline }: { zone: Zone; incidentActive: boolean; simulationDisabled: boolean; time: string; onSimulate: () => void; backendOnline: boolean; realtimeOnline: boolean }) {
  const [expanded, setExpanded] = useState(false);
  useEffect(() => { if (!expanded) return; const key = (e: KeyboardEvent) => { if (e.key === "Escape") setExpanded(false); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [expanded]);
  return <section className={`panel camera-panel ${incidentActive ? "camera-alert" : ""} ${expanded ? "camera-expanded" : ""}`} id="live-camera"><div className="panel-heading"><div><h2><Video size={15}/> CV EVENT MONITOR</h2><p><MapPin size={12}/>{zone.name}<span className="muted-dot">·</span> backend telemetry</p></div><div className="camera-heading-right"><span className="camera-count">{realtimeOnline ? "REALTIME" : "REST"}</span><button className="icon-button" aria-label={expanded ? "Exit expanded view" : "Expand event view"} onClick={() => setExpanded(!expanded)}>{expanded ? <X size={17}/> : <Expand size={16}/>}</button></div></div><div className={`camera-view ${incidentActive ? "critical" : ""}`}><WarehouseScene fallen={incidentActive}/><div className="camera-vignette"/><div className="camera-overlay-top"><span className="camera-id"><Video size={13}/> EVENT VIEW</span><span className="live-label"><i/> {realtimeOnline ? "LIVE DATA" : "OFFLINE"}</span></div><div className={`detection-box ${incidentActive ? "fallen" : ""}`}><span className="detection-label">{incidentActive ? "FALL INCIDENT" : "MONITORING"}<b>{backendOnline ? "API" : "OFF"}</b></span><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/></div>{incidentActive && <div className="camera-warning"><TriangleAlert size={16}/> ACTIVE HIGH-SEVERITY INCIDENT</div>}<div className="camera-bottom"><span>{time || "--"}</span><span>{realtimeOnline ? "WebSocket connected" : "Awaiting realtime connection"}</span></div><span className="scene-label">CV EVENT VISUALIZATION · NOT A CAMERA STREAM</span></div><div className="camera-controls"><div className="vision-status"><ScanLine size={15}/><span>{backendOnline ? "Safety backend connected" : "Backend unavailable"}</span><i/><span className="vision-latency">{realtimeOnline ? "Realtime events active" : "REST fallback"}</span></div><div className="demo-controls"><button className="button simulate-button" disabled={simulationDisabled} onClick={onSimulate}><Zap size={14}/>Send Demo Fall</button></div></div></section>;
}
export function ActiveIncidentCard({ incident, busy, onAcknowledge, onCamera }: { incident?: Incident; busy: boolean; onAcknowledge: () => void; onCamera: () => void }) {
  return <section className={`panel active-panel ${incident ? "active-critical" : ""}`}><div className="panel-heading"><h2><Siren size={15}/> INCIDENT RESPONSE</h2><span className={`tiny-indicator ${incident ? "red" : ""}`}/></div>{!incident ? <div className="all-clear"><div className="safe-orbit"><div><ShieldCheck size={39} strokeWidth={1.4}/></div><i/></div><StatusBadge status="normal">ALL CLEAR</StatusBadge><h3>No unresolved incident</h3><p>The backend currently reports<br/>no active safety incident.</p><div className="all-clear-footer"><CheckCheck size={14}/><span>Realtime detection is standing by</span></div></div> : <div className="incident-content"><div className="incident-title"><div><StatusBadge status={incident.severity}>{incident.status === "acknowledged" ? "ACKNOWLEDGED" : "ACTIVE INCIDENT"}</StatusBadge><h3>{incident.eventType}</h3></div><TriangleAlert size={30}/></div><div className="incident-meta"><div><span>Location</span><b>{incident.zone}</b></div><div><span>Detected</span><b>{formatTime(incident.timestamp, true)}</b></div><div><span>CV confidence</span><b>{incident.confidence}% <span className="confidence-bar"/></b></div><div><span>Severity</span><b className={incident.severity === "critical" ? "red-text" : ""}>{incident.severity.toUpperCase()}</b></div></div><div className={`response-state ${incident.status}`}><span><i/>{incident.status.toUpperCase()}</span><small>SMS: {incident.smsStatus}</small></div><div className="incident-actions"><button className="button secondary" onClick={onAcknowledge} disabled={busy || incident.status !== "unacknowledged"}><Check size={14}/> {incident.status === "acknowledged" ? "Acknowledged" : "Acknowledge"}</button></div><button className="view-camera" onClick={onCamera}><Video size={14}/> View event monitor <ArrowRight size={13}/></button></div>}</section>;
}
export function ZoneStatusPanel({ zones, selected, onSelect }: { zones: Zone[]; selected: string; onSelect: (zone: Zone) => void }) {
  return <section className="panel zones-panel"><div className="panel-heading"><h2><MapPin size={15}/> TRANSIT ZONES</h2><span className="small-label">{zones.length} MONITORED</span></div><div className="zone-list">{zones.map(zone => <button className={`zone-row ${selected === zone.id ? "selected" : ""} ${zone.status}`} key={zone.id} onClick={() => onSelect(zone)}><span className="zone-icon">{zone.status === "critical" ? <TriangleAlert size={17}/> : <ScanLine size={17}/>}</span><span className="zone-info"><b>{zone.name}</b><span><i/>{zone.status === "critical" ? "CRITICAL" : "Normal"}<em>·</em>{zone.incidentsToday} {zone.incidentsToday === 1 ? "incident" : "incidents"} today</span></span><ChevronRight size={15}/></button>)}</div><div className="panel-footnote"><i/> All cameras connected <span>4 / 4</span></div></section>;
}
export function SafetyStats({ incidents }: { incidents: Incident[] }) {
  const today = new Date().toDateString();
  const todayRows = incidents.filter(item => new Date(item.timestamp).toDateString() === today);
  const falls = todayRows.filter(item => item.eventType === "Worker Down").length;
  const unresolved = todayRows.filter(item => item.status !== "resolved").length;
  const acknowledged = todayRows.filter(item => item.status === "acknowledged").length;
  const hours = [8, 10, 12, 14, 16, 18];
  const data = hours.map(hour => ({ hour: new Date(2000, 0, 1, hour).toLocaleTimeString("en-US", { hour: "numeric" }), incidents: todayRows.filter(item => new Date(item.timestamp).getHours() === hour).length }));
  return <section className="panel stats-panel"><div className="panel-heading"><h2><Activity size={15}/> TODAY’S SAFETY STATISTICS</h2><span className="small-label">LIVE DATA</span></div><div className="stats-grid">{[{ label: "Incidents Today", value: todayRows.length, icon: Siren, color: "blue" }, { label: "Falls", value: falls, icon: Footprints, color: "amber" }, { label: "Unresolved", value: unresolved, icon: TriangleAlert, color: "amber" }, { label: "Acknowledged", value: acknowledged, icon: CheckCheck, color: "green" }].map(stat => <div className="stat" key={stat.label}><span className={`stat-icon ${stat.color}`}><stat.icon size={15}/></span><span className="stat-value">{stat.value}</span><span className="stat-label">{stat.label}</span></div>)}</div><div className="chart-title"><span>Incidents by hour</span><span><i/> Backend records</span></div><div className="hour-chart"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{ top: 8, right: 10, left: -25, bottom: 0 }}><CartesianGrid vertical={false} stroke="#263032" strokeDasharray="3 5"/><XAxis dataKey="hour" axisLine={false} tickLine={false} tick={{ fill: "#727f83", fontSize: 10 }} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#727f83", fontSize: 10 }} allowDecimals={false}/><Tooltip contentStyle={{ background: "#192225", border: "1px solid #39464a", borderRadius: 8, color: "#e4eded", fontSize: 12 }}/><Area type="monotone" dataKey="incidents" name="Incidents" stroke="#9bbeb2" strokeWidth={2} fillOpacity={0.1} fill="#9bbeb2" dot={{ r: 3 }} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section>;
}
export function IncidentTimeline({ incidents, onSelect }: { incidents: Incident[]; onSelect: (incident: Incident) => void }) {
  return <section className="panel timeline-panel"><div className="panel-heading"><h2><Clock3 size={15}/> RECENT INCIDENTS</h2><span className="small-label">{incidents.length} EVENTS</span></div><div className="timeline-list">{incidents.map(incident => <button key={incident.id} className="timeline-row" onClick={() => onSelect(incident)}><span className={`timeline-node ${incident.severity}`}><i/></span><span className="timeline-body"><span className="timeline-top"><b>{incident.eventType}</b><time>{formatTime(incident.timestamp)}</time></span><span className="timeline-location">{incident.zone}</span><span className={`timeline-status ${incident.status === "resolved" ? "resolved" : incident.severity}`}>{incident.status === "resolved" ? "Resolved" : incident.status === "dispatched" ? "Response dispatched" : incident.severity === "critical" ? "Critical" : "Warning"}</span></span><ChevronRight size={13}/></button>)}</div></section>;
}
export function AISafetyInsights({ zoneId }: { zoneId?: string }) {
  const [loading, setLoading] = useState(false);
  const [answer, setAnswer] = useState<string | null>(null);
  const [mode, setMode] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function analyze() {
    setLoading(true); setError(null);
    try {
      const result = await askSafetyCoach("Summarize the recorded safety pattern for this zone. Identify only evidence supported by the records and suggest reasonable areas to review.", zoneId);
      setAnswer(result.answer); setMode(result.mode);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Safety Coach request failed.");
    } finally { setLoading(false); }
  }
  return <section className="panel ai-panel"><div className="ai-header"><div className="ai-heading"><span className="ai-icon"><Sparkles size={21}/></span><div><h2>AI SAFETY ANALYSIS <span className="ai-tag">BACKEND COACH</span></h2><p>Analyze the incident records currently stored by Call-Help.</p></div></div><button className="button analyze-button" disabled={loading} onClick={analyze}>{loading ? <LoaderCircle size={15} className="spin"/> : <Sparkles size={15}/>} {loading ? "Analyzing incident history..." : "Analyze Incident Patterns"}{!loading && <ArrowRight size={14}/>}</button></div><div aria-live="polite">{error ? <div className="ai-empty"><span>Analysis unavailable</span><p>{error}</p></div> : answer ? <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="analysis-result"><div><span className="analysis-eyebrow">{mode === "gemini" ? "GEMINI SAFETY COACH" : "LOCAL BACKEND SUMMARY"}</span><h3>Recorded incident analysis</h3><p>{answer}</p></div></motion.div> : <div className="ai-empty"><span><span className="mini-sparkle">✧</span> Analyze real incident history.</span><p>The request is sent to the backend Safety Coach and grounded in stored incidents.</p><div className="ai-capabilities"><span><MapPin size={12}/> Zone context</span><span><Clock3 size={12}/> Recorded history</span><span><ShieldCheck size={12}/> Evidence-based review</span></div></div>}</div><div className="ai-disclaimer"><ShieldCheck size={12}/> AI insights support safety review and should not be treated as definitive causal analysis.</div></section>;
}
export function IncidentDrawer({ incident, onDismiss, onResolve }: { incident: Incident | null; onDismiss: () => void; onResolve: (id: string) => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!incident) return; const previous = document.activeElement as HTMLElement; closeRef.current?.focus(); const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => { if (e.key === "Escape") onDismiss(); if (e.key === "Tab") { const items = document.querySelectorAll<HTMLButtonElement>(".incident-drawer button"); const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = old; document.removeEventListener("keydown", key); previous?.focus(); }; }, [incident, onDismiss]);
  return <AnimatePresence>{incident && <div className="drawer-layer"><motion.button aria-label="Dismiss incident details" className="drawer-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onDismiss}/><motion.aside className="incident-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: .22 }}><div className="drawer-header"><h2 id="drawer-title">Incident details</h2><button ref={closeRef} className="icon-button" aria-label="Close drawer" onClick={onDismiss}><X size={20}/></button></div><StatusBadge status={incident.status === "resolved" ? "normal" : incident.severity}>{incident.status === "resolved" ? "RESOLVED" : incident.severity.toUpperCase()}</StatusBadge><h3>{incident.eventType}</h3><div className="drawer-details">{[["Incident ID", incident.id], ["Event Type", incident.eventType], ["Zone", incident.zone], ["Time", formatTime(incident.timestamp, true)], ["Confidence", `${incident.confidence}%`], ["Response Status", incident.status === "dispatched" ? "Dispatched" : incident.status]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><h4>Backend incident data</h4><ul className="signals">{Object.entries(incident.metadata).length ? Object.entries(incident.metadata).map(([key, value]) => <li key={key}><ScanLine size={14}/>{key}: {String(value)}</li>) : <li><ScanLine size={14}/>No additional CV metadata recorded.</li>}</ul><div className="drawer-summary"><h4><Sparkles size={16}/> Incident description</h4><p>{incident.description}</p></div><button className="button resolve-button" disabled={incident.status === "resolved"} onClick={() => onResolve(incident.id)}><CircleCheck size={16}/>{incident.status === "resolved" ? "Incident Closed" : "Close Incident"}</button><p className="drawer-note">Backend record · Review conditions before resolving.</p></motion.aside></div>}</AnimatePresence>;
}
export function AlertToast({ toast, onDismiss }: { toast: { title: string; message: string; critical?: boolean } | null; onDismiss: () => void }) {
  return <AnimatePresence>{toast && <motion.div role="alert" className={`alert-toast ${toast.critical ? "critical" : ""}`} initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}><span className="toast-icon">{toast.critical ? <TriangleAlert size={21}/> : <CircleCheck size={21}/>}</span><div><b>{toast.title}</b><p>{toast.message}</p></div><button className="icon-button" aria-label="Dismiss notification" onClick={onDismiss}><X size={16}/></button></motion.div>}</AnimatePresence>;
}
